#Item textures locations, 16x16. Download in broswer to save and edit them.
Cocaine: http://dl.dropbox.com/u/41217801/SpoutDrugs/Cocaine.png
Weed: http://dl.dropbox.com/u/136953717/marijuanaleaf.png
LoadedBong: http://dl.dropbox.com/u/41217801/SpoutDrugs/LoadedBong.png
EmptyBong: http://dl.dropbox.com/u/41217801/SpoutDrugs/Bong.png
Heroin: http://dl.dropbox.com/u/136953717/largeheroin.png
EmptySyringe: http://dl.dropbox.com/u/41217801/SpoutDrugs/EmptySyringe.png
HeroinSyringe: http://dl.dropbox.com/u/41217801/SpoutDrugs/HeroinSyringe.png
Vodka: http://dl.dropbox.com/u/41217801/SpoutDrugs/Vodka.png
RollingPapers: http://dl.dropbox.com/u/41217801/SpoutDrugs/Rizla.png
Spliff: http://dl.dropbox.com/u/136953717/Spliff.png
GlassPipe: http://dl.dropbox.com/u/41217801/SpoutDrugs/GlassPipe.png
GarrusPlate: http://dl.dropbox.com/u/136953717/platepower.png
MagicMushroom: http://dl.dropbox.com/u/136953717/InfectedMushroom.png
BluePoison: http://dl.dropbox.com/u/136953717/kekuveg.png
Tokaji: http://dl.dropbox.com/u/136953717/tokaji.png
Szolo: http://dl.dropbox.com/u/136953717/szolo.png
Adderal: http://dl.dropbox.com/u/136953717/adderal.png
Borsodi: http://dl.dropbox.com/u/136953717/borsodi.png
Royal: http://dl.dropbox.com/u/136953717/royal.png
Komlo: http://dl.dropbox.com/u/136953717/hophop.png
Ecstacy: http://dl.dropboxusercontent.com/u/136953717/ecstasy.png
LSD: http://dl.dropboxusercontent.com/u/136953717/lsd.png
Meth: http://dl.dropboxusercontent.com/u/136953717/meth.png
DrugSeeds: http://dl.dropboxusercontent.com/u/136953717/seeds.png
JDB: http://dl.dropboxusercontent.com/u/136953717/jackdanielsblack.png
JDO: http://dl.dropboxusercontent.com/u/136953717/jackdanielsorigi.png